# cloudbuild.yaml
steps:
  # copy the Firebase key
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://pokedex_keys/key.json', './key.json']
  # build & push the container image
- name: "gcr.io/kaniko-project/executor:latest"
  args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/$PROJECT_ID/pokedex:latest"]
  # Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'pokedex', '--image', 'gcr.io/$PROJECT_ID/pokedex:latest', '--region', 'europe-west1', '--allow-unauthenticated', '--platform', 'managed']
